name: Publish Docker

on:
  push:

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: excalidraw/excalidraw/client
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
      # - name: Publish to GH Docker registry
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login -u kbariotis --password-stdin
      #     docker build -t docker.pkg.github.com/excalidraw/excalidraw/client:$GITHUB_RUN_NUMBER .
      #     docker tag $GITHUB_SHA docker.pkg.github.com/excalidraw/excalidraw/client:$GITHUB_RUN_NUMBER
      #     docker push docker.pkg.github.com/excalidraw/excalidraw/client:$GITHUB_RUN_NUMBER
      # - uses: docker/build-push-action@v1
      #   with:
      #     username: kbariotis
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     repository: excalidraw/excalidraw
      #     registry: docker.pkg.github.com
      #     tag_with_ref: true
      #     tag_with_sha: true
